// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.538
package suppliers

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "viniciusvasti/cerimonize/view/layout"

func warnIcon() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"text-yellow-500 inline\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-alert-circle\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><line x1=\"12\" x2=\"12\" y1=\"8\" y2=\"12\"></line><line x1=\"12\" x2=\"12.01\" y1=\"16\" y2=\"16\"></line></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func checkMarkIcon() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"text-green-500 inline\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-check\"><path d=\"M20 6 9 17l-5-5\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func Show() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var4 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form class=\"h-full w-full flex flex-col justify-center items-center mt-4 mb-10 gap-5\"><h2 class=\"text-2xl text-left font-semibold text-purple-500\">Fornecedores</h2><ul class=\"w-full flex flex-col gap-3 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><li class=\"flex flex-col gap-2\"><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Buffet <span class=\"text-purple-400 font-semibold text-base\">R$ 5500,00</span></h3><span class=\"font-medium text-purple-500\">Wedding Buffet & Cia</span><hr class=\"border-purple-500 h-[0.25px]\"><span class=\"flex items-center gap-0.5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = warnIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"https://www.google.com.br\" class=\"text-purple-400 underline\">Contrato</a> <span class=\"text-gray-400 text-sm\">(Não assinado)</span></span><p class=\"text-gray-400 text-sm font-light\">Obs: O contrato deve ser assinado até 30 dias antes do evento.</p></li></ul><ul class=\"w-full flex flex-col gap-3 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><li class=\"flex flex-col gap-2\"><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Flores <span class=\"text-purple-400 font-semibold text-base\">R$ 2500,00</span></h3><span class=\"font-medium text-purple-500\">Floricultura Florescer</span><hr class=\"border-purple-500 h-[0.25px]\"><span class=\"flex items-center gap-0.5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = warnIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"https://www.google.com.br\" class=\"text-purple-400 underline\">Contrato</a> <span class=\"text-gray-400 text-sm\">(Não assinado)</span></span><p class=\"text-gray-400 text-sm font-light\">Obs: O contrato deve ser assinado até 10 dias antes do evento.</p></li></ul><ul class=\"w-full flex flex-col gap-3 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><li class=\"flex flex-col gap-2\"><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Movéis de Decoração <span class=\"text-purple-400 font-semibold text-base\">R$ 1500,00</span></h3><span class=\"font-medium text-purple-500\">Wedding Decor</span><hr class=\"border-purple-500 h-[0.25px]\"><span class=\"flex items-center gap-0.5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = checkMarkIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"https://www.google.com.br\" class=\"text-purple-400 underline\">Contrato</a> <span class=\"text-gray-400 text-sm\">(Assinado)</span></span></li></ul><ul class=\"w-full flex flex-col gap-3 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><li class=\"flex flex-col gap-2\"><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Terno do Noivo <span class=\"text-purple-400 font-semibold text-base\">R$ 1500,00</span></h3><span class=\"font-medium text-purple-500\">Terno & Cia</span><hr class=\"border-purple-500 h-[0.25px]\"><span class=\"flex items-center gap-0.5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = checkMarkIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"https://www.google.com.br\" class=\"text-purple-400 underline\">Contrato</a> <span class=\"text-gray-400 text-sm\">(Assinado)</span></span></li></ul><ul class=\"w-full flex flex-col gap-3 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><li class=\"flex flex-col gap-2\"><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Vestido da Noiva <span class=\"text-purple-400 font-semibold text-base\">R$ 3500,00</span></h3><span class=\"font-medium text-purple-500\">Lindas Noivas Vestidos</span><hr class=\"border-purple-500 h-[0.25px]\"><span class=\"flex items-center gap-0.5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = warnIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"https://www.google.com.br\" class=\"text-purple-400 underline\">Contrato</a> <span class=\"text-gray-400 text-sm\">(Não assinado)</span></span><p class=\"text-gray-400 text-sm font-light\">Obs: O contrato deve ser assinado até 7 dias antes do evento.</p></li></ul><ul class=\"w-full flex flex-col gap-3 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><li class=\"flex flex-col gap-2\"><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Film Maker <span class=\"text-purple-400 font-semibold text-base\">R$ 3500,00</span></h3><span class=\"font-medium text-purple-500\">Maria Film Maker</span><hr class=\"border-purple-500 h-[0.25px]\"><span class=\"flex items-center gap-0.5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = warnIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"https://www.google.com.br\" class=\"text-purple-400 underline\">Contrato</a> <span class=\"text-gray-400 text-sm\">(Não assinado)</span></span><p class=\"text-gray-400 text-sm font-light\">Obs: O contrato deve ser assinado até 15 dias antes do evento.</p></li></ul><ul class=\"w-full flex flex-col gap-3 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><li class=\"flex flex-col gap-2\"><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Fotógrafo <span class=\"text-purple-400 font-semibold text-base\">R$ 3500,00</span></h3><span class=\"font-medium text-purple-500\">João Fotógrafo</span><hr class=\"border-purple-500 h-[0.25px]\"><span class=\"flex items-center gap-0.5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = checkMarkIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"https://www.google.com.br\" class=\"text-purple-400 underline\">Contrato</a> <span class=\"text-gray-400 text-sm\">(Assinado)</span></span></li></ul></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base(true).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
