// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.538
package agenda

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "viniciusvasti/cerimonize/view/layout"
import "time"

func Show() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form class=\"h-full w-full flex flex-col justify-center items-center mt-4 mb-10 gap-5\"><h2 class=\"text-2xl text-left font-semibold text-purple-500\">Agenda dos Noivos</h2><div class=\"w-full flex flex-col gap-2 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><span class=\"text-purple-400 font-semibold text-base\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(time.Now().AddDate(0, 2, 0).Format("02/01/2006"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/agenda/show.templ`, Line: 11, Col: 55}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" - 10:00</span><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Degustação do Buffet</h3><span class=\"font-medium text-purple-500\">Wedding Buffet & Cia</span><hr class=\"border-purple-500 h-[0.25px]\"><p class=\"text-gray-400 text-sm font-light\">Rua Barão de Itapetininga, 37 - Centro, São Paulo - SP, 01042-001</p></div><div class=\"w-full flex flex-col gap-2 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><span class=\"text-purple-400 font-semibold text-base\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(time.Now().AddDate(0, 1, 15).Format("02/01/2006"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/agenda/show.templ`, Line: 24, Col: 56}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" - 14:00</span><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Escolha dos Movéis de Decoração</h3><span class=\"font-medium text-purple-500\">Wedding Decor</span><hr class=\"border-purple-500 h-[0.25px]\"><p class=\"text-gray-400 text-sm font-light\">Avenida Paulista, 1000 - Bela Vista, São Paulo - SP, 01310-100</p></div><div class=\"w-full flex flex-col gap-2 bg-gray-50 p-6 rounded-lg border-2 border-purple-500 shadow-lg\"><span class=\"text-purple-400 font-semibold text-base\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(time.Now().AddDate(0, 2, 10).Format("02/01/2006"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/agenda/show.templ`, Line: 39, Col: 56}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" - 09:00</span><h3 class=\"flex flex-row justify-between text-lg font-semi text-purple-900\">Escolha das Flores</h3><span class=\"font-medium text-purple-500\">Floricultura Florescer</span><hr class=\"border-purple-500 h-[0.25px]\"><p class=\"text-gray-400 text-sm font-light\">Rua Augusta, 1000 - Consolação, São Paulo - SP, 01304-001</p></div><div class=\"w-full flex flex-col gap-2 bg-gray-50 p-6 rounded-lg border-2 border-gray-300 shadow-lg\"><h3 class=\"flex flex-row justify-between text-lg font-semi text-gray-300\">Prova do Terno do Noivo <span class=\"text-gray-300 font-semibold text-base\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(time.Now().AddDate(0, 0, -10).Format("02/01/2006"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/agenda/show.templ`, Line: 54, Col: 58}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" - 10:00</span></h3><span class=\"font-medium text-gray-300\">Terno & Cia</span><hr class=\"border-gray-300 h-[0.25px]\"><p class=\"text-gray-300 text-sm font-light underline\">Rua dos Bobos, 0 - Centro, São Paulo - SP, 00000-000</p></div></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base(true).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
