// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.538
package inspirations

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "viniciusvasti/cerimonize/view/layout"

func Show() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"h-full w-full flex flex-col justify-center items-center mt-4 mb-10 gap-5\"><h2 class=\"text-2xl text-left font-semibold text-purple-500\">Inspirações</h2><div><img src=\"/public/img/inspiration1.jpeg\" alt=\"Image 1\" class=\"w-screen border-1 rounded-3xl border-black shadow-lg\"><div class=\"mt-5 text-sm text-gray-500 italic\">Postado por: Maria (Noiva)<p class=\"text-base text-gray-500 italic\">Eu gostaria que nossa decoração fosse nesse estilo.</p></div></div><div class=\"w-full space-y-4\"><div class=\"flex items-center\"><textarea placeholder=\"Adicione um comentário...\" class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring focus:border-blue-300\"></textarea></div><div><div class=\"flex items-center justify-between\"><p class=\"text-sm font-semibold text-purple-900\">Ariel (Cerimonialista)</p><p class=\"text-xs text-gray-400\">1 dia atrás</p></div><p class=\"text-sm mt-1 text-purple-500\">Gostei, Maria. Vamos trabalhar nessa ideia!</p></div><div><div class=\"flex items-center justify-between\"><p class=\"text-sm font-semibold text-purple-900\">João (Noivo)</p><p class=\"text-xs text-gray-400\">2 dias atrás</p></div><p class=\"text-sm mt-1 text-purple-500\">Adorei, amor!</p></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base(true).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
